apiVersion: v1
kind: Pod
metadata: 
  name: pvc-demo-pod
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: web-storage
  volumes:
  - name: web-storage
    persistentVolumeClaim:
      claimName: demo-pvc
